### ISSUE TITLE
401 Unauthorized on calls to /api endpoints

### ISSUE THREAD

**Issue by gmer16** [OsiriX-Foundation/KheopsAuthorization#28]
Hi, 
I'm trying to deploy a Kheops instance on two Ubuntu 18.04 VMs running on the cloud, one for Kheops and the other for Keycloak. I configured Keycloak as suggested in the official docs. For both VMs I've setup separate domains with SSL certificates.
All the authentication flow seems to work, I'm able to create users, login into the 'cockpit', and also the call to the `/token` endpoint to exchange the authorization code for an access token succeeds, but when the UI tries to access the `/api` endopints to load the study list or the albums list the calls return with `401 Unauthorized`.
Checking the logs for the `kheopsauthorization` container I can see that each call generates an exception:

`07:09:22.915 [http-nio-8080-exec-8] DEBUG org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl - Initiating JDBC connection release from afterTransaction
04-Mar-2020 07:09:22.916 WARNING [http-nio-8080-exec-8] online.kheops.auth_server.user.Users.getOrCreateUser User was not found in the db, going on to try to add the user
        online.kheops.auth_server.user.UserNotFoundException`

Do you have any clue of what might be the reason for this problem?
I previously copied the 'secret' for the Keycloak` kheopsAuthorization` Client inside the `/kheops/secrets/kheops_keycloak_clientsecret` file before starting the system, so that shouldn't be the problem.

Thanks

**Comment by spalte** [comment]
It's hard to say what is happening exactly from your description. My initial suspicion, and yours also if I understand correctly, is that there is a misconfiguration at the level of the Keycloak server.

Based on what you describe, here are my thoughts:
1. When the KHEOPS Authorization Server processes an Access Token it first needs to connect to Keycloak to obtain the RSA public key to validate the Access Token signature. Since the logs are from after validation, the KHEOPS Authorization Server must have been able to connect to the Keycloak VM.
2. The KHEOPS Authorization Server then looks up the user in its database and, not surprisingly since the user has never connected before, the user is not found. It then queries the Keycloak server using the kheopsAuthorization Client (using the client secret) and uses Keycloak proprietary APIs to get more information about the user. If this does not work, the KHEOPS Authorization Server will reject the Access Token.

One thing that is easy to miss in the Keycloak configuration is that both the kheopsAuthorization Client and the Service Account need to have view-users privileges. In other words, the client needs the privilege itself in order to provide the service to the specific users (the service account in this case) who have the privilege.

If this is not the problem, then I am a bit stumped and can only invite you to send me an email so that we might continue to work on figuring out what is going on.

**Comment by gmer16** [comment]
Hi, thanks for the explanation.
It turns out the problem was related to a CORS configuration issue in Keycloak.
Looking at the Keycloak logs, the only unusual thing that I could notice around the time 
the request was rejected was a warning saying something like "No web origin header present: ignoring".
I then followed the suggestion at this link https://github.com/mauriciovigolo/keycloak-angular/issues/91#issuecomment-477852747 to modify the configuration of the _kheopsAuthorization_ client, and after that the _/api_ calls succeed.
The reason is probably that in my setup the two VMs for kheops and keycloak are running under two different domain names.

![Screenshot from 2020-03-06 12-34-49](https://user-images.githubusercontent.com/20323593/76233334-f14bb400-621f-11ea-9cae-bee66288b1f2.png)
