### ISSUE TITLE
kheops-authorization failes

### ISSUE THREAD

**Issue by fswm3i** [OsiriX-Foundation/KheopsAuthorization#29]
Hi, 
I'm trying to set up a secure instance. Keycloak and Kheops are available from outside and secured. Sadly, after creating a new kheops-user and trying to log on, a loading-animation is shown for a few minutes, while the only thing that happens in the logs is:
`
18:29:06.429 [main] INFO liquibase.executor.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
18:29:06.430 [main] INFO liquibase.lockservice.StandardLockService - Waiting for changelog lock....
18:29:16.431 [main] INFO liquibase.executor.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
18:29:16.433 [main] INFO liquibase.lockservice.StandardLockService - Waiting for changelog lock....
18:29:26.435 [main] INFO liquibase.executor.jvm.JdbcExecutor - SELECT LOCKED FROM public.databasechangeloglock WHERE ID=1
` 

After that the kheops-auth-container crashes, see log attached. The GUI reads "An error occured please reload the studies."

Any idea how to proceed?
Thanks
Felix

[kheops-auth.log](https://github.com/OsiriX-Foundation/KheopsAuthorization/files/5460681/kheops-auth.log)

**Comment by spalte** [comment]
Hi,

It looks like there is a problem acquiring a database lock at launch when liquibase checks the status of the database.

It’s hard for me to say what happened, or how to fix it without more info. I can’t think of any way this could be related to creating a new user. I would suspect something more like the system getting killed at just the wrong moment without having a chance to release a lock... or something...

It sounds like you are just setting up the server though, so if there is no valuable data stored yet, I would recommend removing (deleting) the kheops-db-data volume that is attached to the kheops-postgres container. Once you reboot the system, docker-compose should recreate the volume, the postgres server will reinitialize a new database, and liquibase in kheopsauthorization will rebuild all the necessary tables and such.

Cheers,
Joël

**Comment by gerome12** [comment]
Hi Felix,

I think the issue is that Liquibase use a table `databasechangeloglock `  with a boolean `locked` and for an unknown reason, this boolean is set to `true` and the database is locked.

I see two solutions :

- set the lock to false manually 
if you use docker you can do the commands below :  
`docker exec -it kheopspostgres bash` where kheopspostgres  is the container name
`psql -Ukheopsuser kheops` where kheopsuser is the username and kheops is the db name
`SELECT * FROM public.databasechangeloglock;`
`UPDATE public.databasechangeloglock SET locked = false WHERE id = 1;`

- clear all the database and restart kheops 
if you use docker you can remove the volume of the database (only if the database is empty because you will lose all the data)
docker volume rm <volume name>
or 
clear all kheops and restart with
`docker-compose down -v`
`docker-compose up -d`

Gérôme

**Comment by fswm3i** [comment]
Thanks guys, I'll give it a go tomorrow and get back to you

**Comment by fswm3i** [comment]
Thanks for your help. We deployed the containers to an AWS instance for testing, which resolved our issue. Didn't have the chance to try and fix the problem locally
